apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-configmap
  namespace: mtta
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS microservice_db;
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
