# spring:
#   datasource:
#     url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}
#     username: ${DB_USER}
#     password: ${DB_PASSWORD}
#   jpa:
#     hibernate:
#       ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:db}:3306/${DB_DATABASE:microservice_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
