name: CICD
on: workflow_dispatch
env:
  BACKEND_IMAGE: swaroops2803/mtta_backend
  FRONTEND_IMAGE: swaroops2803/mtta_frontend
  K8S_NAMESPACE: mtta
  AWS_REGION: eu-north-1
  EKS_CLUSTER_NAME: EKS_Cluster
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Builds
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{env.BACKEND_IMAGE}}:latest
            ${{env.BACKEND_IMAGE}}:${{github.run_number}}

      - name: Build and push frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{env.FRONTEND_IMAGE}}:latest
            ${{env.FRONTEND_IMAGE}}:${{github.run_number}}

      - name: Update image tags in manifests
        run: |
          sed -i "s|swaroops2803/mtta_backend:.*|swaroops2803/mtta_backend:${{ github.run_number }}|g" k8s/backend-deployment.yml
          sed -i "s|swaroops2803/mtta_frontend:.*|swaroops2803/mtta_frontend:${{ github.run_number }}|g" k8s/frontend-deployment.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Verify Kubernetes connection
        run: kubectl get nodes

      - name: Create namespace if missing
        run: kubectl get ns ${{ env.K8S_NAMESPACE }} || kubectl create ns ${{ env.K8S_NAMESPACE }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/secrets.yml
          kubectl apply -f k8s/configmap.yml
          kubectl apply -f k8s/mysql-initdb-config-map.yml
          kubectl apply -f k8s/mysql-deployment.yml
          kubectl apply -f k8s/mysql-service.yml
          kubectl apply -f k8s/backend-deployment.yml
          kubectl apply -f k8s/backend-service.yml
          kubectl apply -f k8s/frontend-deployment.yml
          kubectl apply -f k8s/frontend-service.yml

      - name: Show services
        run: kubectl get svc -n ${{ env.K8S_NAMESPACE }}
